// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package payment;

public final class Payment {
  private Payment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreditCardInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:payment.CreditCardInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string credit_card_number = 1;</code>
     * @return The creditCardNumber.
     */
    java.lang.String getCreditCardNumber();
    /**
     * <code>string credit_card_number = 1;</code>
     * @return The bytes for creditCardNumber.
     */
    com.google.protobuf.ByteString
        getCreditCardNumberBytes();

    /**
     * <code>int32 credit_card_cvv = 2;</code>
     * @return The creditCardCvv.
     */
    int getCreditCardCvv();

    /**
     * <code>int32 credit_card_expiration_year = 3;</code>
     * @return The creditCardExpirationYear.
     */
    int getCreditCardExpirationYear();

    /**
     * <code>int32 credit_card_expiration_month = 4;</code>
     * @return The creditCardExpirationMonth.
     */
    int getCreditCardExpirationMonth();
  }
  /**
   * Protobuf type {@code payment.CreditCardInfo}
   */
  public static final class CreditCardInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:payment.CreditCardInfo)
      CreditCardInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreditCardInfo.newBuilder() to construct.
    private CreditCardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreditCardInfo() {
      creditCardNumber_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreditCardInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return payment.Payment.internal_static_payment_CreditCardInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return payment.Payment.internal_static_payment_CreditCardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              payment.Payment.CreditCardInfo.class, payment.Payment.CreditCardInfo.Builder.class);
    }

    public static final int CREDIT_CARD_NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object creditCardNumber_;
    /**
     * <code>string credit_card_number = 1;</code>
     * @return The creditCardNumber.
     */
    @java.lang.Override
    public java.lang.String getCreditCardNumber() {
      java.lang.Object ref = creditCardNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creditCardNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string credit_card_number = 1;</code>
     * @return The bytes for creditCardNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreditCardNumberBytes() {
      java.lang.Object ref = creditCardNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creditCardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREDIT_CARD_CVV_FIELD_NUMBER = 2;
    private int creditCardCvv_;
    /**
     * <code>int32 credit_card_cvv = 2;</code>
     * @return The creditCardCvv.
     */
    @java.lang.Override
    public int getCreditCardCvv() {
      return creditCardCvv_;
    }

    public static final int CREDIT_CARD_EXPIRATION_YEAR_FIELD_NUMBER = 3;
    private int creditCardExpirationYear_;
    /**
     * <code>int32 credit_card_expiration_year = 3;</code>
     * @return The creditCardExpirationYear.
     */
    @java.lang.Override
    public int getCreditCardExpirationYear() {
      return creditCardExpirationYear_;
    }

    public static final int CREDIT_CARD_EXPIRATION_MONTH_FIELD_NUMBER = 4;
    private int creditCardExpirationMonth_;
    /**
     * <code>int32 credit_card_expiration_month = 4;</code>
     * @return The creditCardExpirationMonth.
     */
    @java.lang.Override
    public int getCreditCardExpirationMonth() {
      return creditCardExpirationMonth_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creditCardNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, creditCardNumber_);
      }
      if (creditCardCvv_ != 0) {
        output.writeInt32(2, creditCardCvv_);
      }
      if (creditCardExpirationYear_ != 0) {
        output.writeInt32(3, creditCardExpirationYear_);
      }
      if (creditCardExpirationMonth_ != 0) {
        output.writeInt32(4, creditCardExpirationMonth_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creditCardNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, creditCardNumber_);
      }
      if (creditCardCvv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, creditCardCvv_);
      }
      if (creditCardExpirationYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, creditCardExpirationYear_);
      }
      if (creditCardExpirationMonth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, creditCardExpirationMonth_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof payment.Payment.CreditCardInfo)) {
        return super.equals(obj);
      }
      payment.Payment.CreditCardInfo other = (payment.Payment.CreditCardInfo) obj;

      if (!getCreditCardNumber()
          .equals(other.getCreditCardNumber())) return false;
      if (getCreditCardCvv()
          != other.getCreditCardCvv()) return false;
      if (getCreditCardExpirationYear()
          != other.getCreditCardExpirationYear()) return false;
      if (getCreditCardExpirationMonth()
          != other.getCreditCardExpirationMonth()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CREDIT_CARD_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getCreditCardNumber().hashCode();
      hash = (37 * hash) + CREDIT_CARD_CVV_FIELD_NUMBER;
      hash = (53 * hash) + getCreditCardCvv();
      hash = (37 * hash) + CREDIT_CARD_EXPIRATION_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getCreditCardExpirationYear();
      hash = (37 * hash) + CREDIT_CARD_EXPIRATION_MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getCreditCardExpirationMonth();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static payment.Payment.CreditCardInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.CreditCardInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.CreditCardInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.Payment.CreditCardInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static payment.Payment.CreditCardInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.Payment.CreditCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(payment.Payment.CreditCardInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code payment.CreditCardInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:payment.CreditCardInfo)
        payment.Payment.CreditCardInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.Payment.internal_static_payment_CreditCardInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.Payment.internal_static_payment_CreditCardInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.Payment.CreditCardInfo.class, payment.Payment.CreditCardInfo.Builder.class);
      }

      // Construct using payment.Payment.CreditCardInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        creditCardNumber_ = "";

        creditCardCvv_ = 0;

        creditCardExpirationYear_ = 0;

        creditCardExpirationMonth_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return payment.Payment.internal_static_payment_CreditCardInfo_descriptor;
      }

      @java.lang.Override
      public payment.Payment.CreditCardInfo getDefaultInstanceForType() {
        return payment.Payment.CreditCardInfo.getDefaultInstance();
      }

      @java.lang.Override
      public payment.Payment.CreditCardInfo build() {
        payment.Payment.CreditCardInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public payment.Payment.CreditCardInfo buildPartial() {
        payment.Payment.CreditCardInfo result = new payment.Payment.CreditCardInfo(this);
        result.creditCardNumber_ = creditCardNumber_;
        result.creditCardCvv_ = creditCardCvv_;
        result.creditCardExpirationYear_ = creditCardExpirationYear_;
        result.creditCardExpirationMonth_ = creditCardExpirationMonth_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof payment.Payment.CreditCardInfo) {
          return mergeFrom((payment.Payment.CreditCardInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(payment.Payment.CreditCardInfo other) {
        if (other == payment.Payment.CreditCardInfo.getDefaultInstance()) return this;
        if (!other.getCreditCardNumber().isEmpty()) {
          creditCardNumber_ = other.creditCardNumber_;
          onChanged();
        }
        if (other.getCreditCardCvv() != 0) {
          setCreditCardCvv(other.getCreditCardCvv());
        }
        if (other.getCreditCardExpirationYear() != 0) {
          setCreditCardExpirationYear(other.getCreditCardExpirationYear());
        }
        if (other.getCreditCardExpirationMonth() != 0) {
          setCreditCardExpirationMonth(other.getCreditCardExpirationMonth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                creditCardNumber_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                creditCardCvv_ = input.readInt32();

                break;
              } // case 16
              case 24: {
                creditCardExpirationYear_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                creditCardExpirationMonth_ = input.readInt32();

                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object creditCardNumber_ = "";
      /**
       * <code>string credit_card_number = 1;</code>
       * @return The creditCardNumber.
       */
      public java.lang.String getCreditCardNumber() {
        java.lang.Object ref = creditCardNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creditCardNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string credit_card_number = 1;</code>
       * @return The bytes for creditCardNumber.
       */
      public com.google.protobuf.ByteString
          getCreditCardNumberBytes() {
        java.lang.Object ref = creditCardNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creditCardNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string credit_card_number = 1;</code>
       * @param value The creditCardNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCreditCardNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        creditCardNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string credit_card_number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreditCardNumber() {
        
        creditCardNumber_ = getDefaultInstance().getCreditCardNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string credit_card_number = 1;</code>
       * @param value The bytes for creditCardNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCreditCardNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        creditCardNumber_ = value;
        onChanged();
        return this;
      }

      private int creditCardCvv_ ;
      /**
       * <code>int32 credit_card_cvv = 2;</code>
       * @return The creditCardCvv.
       */
      @java.lang.Override
      public int getCreditCardCvv() {
        return creditCardCvv_;
      }
      /**
       * <code>int32 credit_card_cvv = 2;</code>
       * @param value The creditCardCvv to set.
       * @return This builder for chaining.
       */
      public Builder setCreditCardCvv(int value) {
        
        creditCardCvv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 credit_card_cvv = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreditCardCvv() {
        
        creditCardCvv_ = 0;
        onChanged();
        return this;
      }

      private int creditCardExpirationYear_ ;
      /**
       * <code>int32 credit_card_expiration_year = 3;</code>
       * @return The creditCardExpirationYear.
       */
      @java.lang.Override
      public int getCreditCardExpirationYear() {
        return creditCardExpirationYear_;
      }
      /**
       * <code>int32 credit_card_expiration_year = 3;</code>
       * @param value The creditCardExpirationYear to set.
       * @return This builder for chaining.
       */
      public Builder setCreditCardExpirationYear(int value) {
        
        creditCardExpirationYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 credit_card_expiration_year = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreditCardExpirationYear() {
        
        creditCardExpirationYear_ = 0;
        onChanged();
        return this;
      }

      private int creditCardExpirationMonth_ ;
      /**
       * <code>int32 credit_card_expiration_month = 4;</code>
       * @return The creditCardExpirationMonth.
       */
      @java.lang.Override
      public int getCreditCardExpirationMonth() {
        return creditCardExpirationMonth_;
      }
      /**
       * <code>int32 credit_card_expiration_month = 4;</code>
       * @param value The creditCardExpirationMonth to set.
       * @return This builder for chaining.
       */
      public Builder setCreditCardExpirationMonth(int value) {
        
        creditCardExpirationMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 credit_card_expiration_month = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreditCardExpirationMonth() {
        
        creditCardExpirationMonth_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:payment.CreditCardInfo)
    }

    // @@protoc_insertion_point(class_scope:payment.CreditCardInfo)
    private static final payment.Payment.CreditCardInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new payment.Payment.CreditCardInfo();
    }

    public static payment.Payment.CreditCardInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreditCardInfo>
        PARSER = new com.google.protobuf.AbstractParser<CreditCardInfo>() {
      @java.lang.Override
      public CreditCardInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreditCardInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreditCardInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public payment.Payment.CreditCardInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChargeReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:payment.ChargeReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float amount = 1;</code>
     * @return The amount.
     */
    float getAmount();

    /**
     * <code>.payment.CreditCardInfo credit_card = 2;</code>
     * @return Whether the creditCard field is set.
     */
    boolean hasCreditCard();
    /**
     * <code>.payment.CreditCardInfo credit_card = 2;</code>
     * @return The creditCard.
     */
    payment.Payment.CreditCardInfo getCreditCard();
    /**
     * <code>.payment.CreditCardInfo credit_card = 2;</code>
     */
    payment.Payment.CreditCardInfoOrBuilder getCreditCardOrBuilder();

    /**
     * <code>string order_id = 3;</code>
     * @return The orderId.
     */
    java.lang.String getOrderId();
    /**
     * <code>string order_id = 3;</code>
     * @return The bytes for orderId.
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>uint32 user_id = 4;</code>
     * @return The userId.
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code payment.ChargeReq}
   */
  public static final class ChargeReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:payment.ChargeReq)
      ChargeReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChargeReq.newBuilder() to construct.
    private ChargeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChargeReq() {
      orderId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChargeReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return payment.Payment.internal_static_payment_ChargeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return payment.Payment.internal_static_payment_ChargeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              payment.Payment.ChargeReq.class, payment.Payment.ChargeReq.Builder.class);
    }

    public static final int AMOUNT_FIELD_NUMBER = 1;
    private float amount_;
    /**
     * <code>float amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public float getAmount() {
      return amount_;
    }

    public static final int CREDIT_CARD_FIELD_NUMBER = 2;
    private payment.Payment.CreditCardInfo creditCard_;
    /**
     * <code>.payment.CreditCardInfo credit_card = 2;</code>
     * @return Whether the creditCard field is set.
     */
    @java.lang.Override
    public boolean hasCreditCard() {
      return creditCard_ != null;
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 2;</code>
     * @return The creditCard.
     */
    @java.lang.Override
    public payment.Payment.CreditCardInfo getCreditCard() {
      return creditCard_ == null ? payment.Payment.CreditCardInfo.getDefaultInstance() : creditCard_;
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 2;</code>
     */
    @java.lang.Override
    public payment.Payment.CreditCardInfoOrBuilder getCreditCardOrBuilder() {
      return getCreditCard();
    }

    public static final int ORDER_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string order_id = 3;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string order_id = 3;</code>
     * @return The bytes for orderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 4;
    private int userId_;
    /**
     * <code>uint32 user_id = 4;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(amount_) != 0) {
        output.writeFloat(1, amount_);
      }
      if (creditCard_ != null) {
        output.writeMessage(2, getCreditCard());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orderId_);
      }
      if (userId_ != 0) {
        output.writeUInt32(4, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(amount_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, amount_);
      }
      if (creditCard_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCreditCard());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orderId_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof payment.Payment.ChargeReq)) {
        return super.equals(obj);
      }
      payment.Payment.ChargeReq other = (payment.Payment.ChargeReq) obj;

      if (java.lang.Float.floatToIntBits(getAmount())
          != java.lang.Float.floatToIntBits(
              other.getAmount())) return false;
      if (hasCreditCard() != other.hasCreditCard()) return false;
      if (hasCreditCard()) {
        if (!getCreditCard()
            .equals(other.getCreditCard())) return false;
      }
      if (!getOrderId()
          .equals(other.getOrderId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
      if (hasCreditCard()) {
        hash = (37 * hash) + CREDIT_CARD_FIELD_NUMBER;
        hash = (53 * hash) + getCreditCard().hashCode();
      }
      hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static payment.Payment.ChargeReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.ChargeReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.ChargeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.ChargeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.ChargeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.ChargeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.ChargeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.Payment.ChargeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.Payment.ChargeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static payment.Payment.ChargeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.Payment.ChargeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.Payment.ChargeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(payment.Payment.ChargeReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code payment.ChargeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:payment.ChargeReq)
        payment.Payment.ChargeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.Payment.internal_static_payment_ChargeReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.Payment.internal_static_payment_ChargeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.Payment.ChargeReq.class, payment.Payment.ChargeReq.Builder.class);
      }

      // Construct using payment.Payment.ChargeReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        amount_ = 0F;

        if (creditCardBuilder_ == null) {
          creditCard_ = null;
        } else {
          creditCard_ = null;
          creditCardBuilder_ = null;
        }
        orderId_ = "";

        userId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return payment.Payment.internal_static_payment_ChargeReq_descriptor;
      }

      @java.lang.Override
      public payment.Payment.ChargeReq getDefaultInstanceForType() {
        return payment.Payment.ChargeReq.getDefaultInstance();
      }

      @java.lang.Override
      public payment.Payment.ChargeReq build() {
        payment.Payment.ChargeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public payment.Payment.ChargeReq buildPartial() {
        payment.Payment.ChargeReq result = new payment.Payment.ChargeReq(this);
        result.amount_ = amount_;
        if (creditCardBuilder_ == null) {
          result.creditCard_ = creditCard_;
        } else {
          result.creditCard_ = creditCardBuilder_.build();
        }
        result.orderId_ = orderId_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof payment.Payment.ChargeReq) {
          return mergeFrom((payment.Payment.ChargeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(payment.Payment.ChargeReq other) {
        if (other == payment.Payment.ChargeReq.getDefaultInstance()) return this;
        if (other.getAmount() != 0F) {
          setAmount(other.getAmount());
        }
        if (other.hasCreditCard()) {
          mergeCreditCard(other.getCreditCard());
        }
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                amount_ = input.readFloat();

                break;
              } // case 13
              case 18: {
                input.readMessage(
                    getCreditCardFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              case 26: {
                orderId_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                userId_ = input.readUInt32();

                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private float amount_ ;
      /**
       * <code>float amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>float amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(float value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0F;
        onChanged();
        return this;
      }

      private payment.Payment.CreditCardInfo creditCard_;
      private com.google.protobuf.SingleFieldBuilderV3<
          payment.Payment.CreditCardInfo, payment.Payment.CreditCardInfo.Builder, payment.Payment.CreditCardInfoOrBuilder> creditCardBuilder_;
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       * @return Whether the creditCard field is set.
       */
      public boolean hasCreditCard() {
        return creditCardBuilder_ != null || creditCard_ != null;
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       * @return The creditCard.
       */
      public payment.Payment.CreditCardInfo getCreditCard() {
        if (creditCardBuilder_ == null) {
          return creditCard_ == null ? payment.Payment.CreditCardInfo.getDefaultInstance() : creditCard_;
        } else {
          return creditCardBuilder_.getMessage();
        }
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      public Builder setCreditCard(payment.Payment.CreditCardInfo value) {
        if (creditCardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          creditCard_ = value;
          onChanged();
        } else {
          creditCardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      public Builder setCreditCard(
          payment.Payment.CreditCardInfo.Builder builderForValue) {
        if (creditCardBuilder_ == null) {
          creditCard_ = builderForValue.build();
          onChanged();
        } else {
          creditCardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      public Builder mergeCreditCard(payment.Payment.CreditCardInfo value) {
        if (creditCardBuilder_ == null) {
          if (creditCard_ != null) {
            creditCard_ =
              payment.Payment.CreditCardInfo.newBuilder(creditCard_).mergeFrom(value).buildPartial();
          } else {
            creditCard_ = value;
          }
          onChanged();
        } else {
          creditCardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      public Builder clearCreditCard() {
        if (creditCardBuilder_ == null) {
          creditCard_ = null;
          onChanged();
        } else {
          creditCard_ = null;
          creditCardBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      public payment.Payment.CreditCardInfo.Builder getCreditCardBuilder() {
        
        onChanged();
        return getCreditCardFieldBuilder().getBuilder();
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      public payment.Payment.CreditCardInfoOrBuilder getCreditCardOrBuilder() {
        if (creditCardBuilder_ != null) {
          return creditCardBuilder_.getMessageOrBuilder();
        } else {
          return creditCard_ == null ?
              payment.Payment.CreditCardInfo.getDefaultInstance() : creditCard_;
        }
      }
      /**
       * <code>.payment.CreditCardInfo credit_card = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          payment.Payment.CreditCardInfo, payment.Payment.CreditCardInfo.Builder, payment.Payment.CreditCardInfoOrBuilder> 
          getCreditCardFieldBuilder() {
        if (creditCardBuilder_ == null) {
          creditCardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              payment.Payment.CreditCardInfo, payment.Payment.CreditCardInfo.Builder, payment.Payment.CreditCardInfoOrBuilder>(
                  getCreditCard(),
                  getParentForChildren(),
                  isClean());
          creditCard_ = null;
        }
        return creditCardBuilder_;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string order_id = 3;</code>
       * @return The orderId.
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string order_id = 3;</code>
       * @return The bytes for orderId.
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string order_id = 3;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string order_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string order_id = 3;</code>
       * @param value The bytes for orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>uint32 user_id = 4;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>uint32 user_id = 4;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 user_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:payment.ChargeReq)
    }

    // @@protoc_insertion_point(class_scope:payment.ChargeReq)
    private static final payment.Payment.ChargeReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new payment.Payment.ChargeReq();
    }

    public static payment.Payment.ChargeReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChargeReq>
        PARSER = new com.google.protobuf.AbstractParser<ChargeReq>() {
      @java.lang.Override
      public ChargeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChargeReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChargeReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public payment.Payment.ChargeReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChargeRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:payment.ChargeResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    java.lang.String getTransactionId();
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();
  }
  /**
   * Protobuf type {@code payment.ChargeResp}
   */
  public static final class ChargeResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:payment.ChargeResp)
      ChargeRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChargeResp.newBuilder() to construct.
    private ChargeResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChargeResp() {
      transactionId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChargeResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return payment.Payment.internal_static_payment_ChargeResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return payment.Payment.internal_static_payment_ChargeResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              payment.Payment.ChargeResp.class, payment.Payment.ChargeResp.Builder.class);
    }

    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object transactionId_;
    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    @java.lang.Override
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transactionId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transactionId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof payment.Payment.ChargeResp)) {
        return super.equals(obj);
      }
      payment.Payment.ChargeResp other = (payment.Payment.ChargeResp) obj;

      if (!getTransactionId()
          .equals(other.getTransactionId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static payment.Payment.ChargeResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.ChargeResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.ChargeResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.ChargeResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.ChargeResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.Payment.ChargeResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.Payment.ChargeResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.Payment.ChargeResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.Payment.ChargeResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static payment.Payment.ChargeResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.Payment.ChargeResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.Payment.ChargeResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(payment.Payment.ChargeResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code payment.ChargeResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:payment.ChargeResp)
        payment.Payment.ChargeRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.Payment.internal_static_payment_ChargeResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.Payment.internal_static_payment_ChargeResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.Payment.ChargeResp.class, payment.Payment.ChargeResp.Builder.class);
      }

      // Construct using payment.Payment.ChargeResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        transactionId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return payment.Payment.internal_static_payment_ChargeResp_descriptor;
      }

      @java.lang.Override
      public payment.Payment.ChargeResp getDefaultInstanceForType() {
        return payment.Payment.ChargeResp.getDefaultInstance();
      }

      @java.lang.Override
      public payment.Payment.ChargeResp build() {
        payment.Payment.ChargeResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public payment.Payment.ChargeResp buildPartial() {
        payment.Payment.ChargeResp result = new payment.Payment.ChargeResp(this);
        result.transactionId_ = transactionId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof payment.Payment.ChargeResp) {
          return mergeFrom((payment.Payment.ChargeResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(payment.Payment.ChargeResp other) {
        if (other == payment.Payment.ChargeResp.getDefaultInstance()) return this;
        if (!other.getTransactionId().isEmpty()) {
          transactionId_ = other.transactionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                transactionId_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object transactionId_ = "";
      /**
       * <code>string transaction_id = 1;</code>
       * @return The transactionId.
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @return The bytes for transactionId.
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @param value The transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionId() {
        
        transactionId_ = getDefaultInstance().getTransactionId();
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @param value The bytes for transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transactionId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:payment.ChargeResp)
    }

    // @@protoc_insertion_point(class_scope:payment.ChargeResp)
    private static final payment.Payment.ChargeResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new payment.Payment.ChargeResp();
    }

    public static payment.Payment.ChargeResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChargeResp>
        PARSER = new com.google.protobuf.AbstractParser<ChargeResp>() {
      @java.lang.Override
      public ChargeResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChargeResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChargeResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public payment.Payment.ChargeResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_CreditCardInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_CreditCardInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_ChargeReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_ChargeReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_ChargeResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_ChargeResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\022\007payment\"\220\001\n\016CreditCardI" +
      "nfo\022\032\n\022credit_card_number\030\001 \001(\t\022\027\n\017credi" +
      "t_card_cvv\030\002 \001(\005\022#\n\033credit_card_expirati" +
      "on_year\030\003 \001(\005\022$\n\034credit_card_expiration_" +
      "month\030\004 \001(\005\"l\n\tChargeReq\022\016\n\006amount\030\001 \001(\002" +
      "\022,\n\013credit_card\030\002 \001(\0132\027.payment.CreditCa" +
      "rdInfo\022\020\n\010order_id\030\003 \001(\t\022\017\n\007user_id\030\004 \001(" +
      "\r\"$\n\nChargeResp\022\026\n\016transaction_id\030\001 \001(\t2" +
      "E\n\016PaymentService\0223\n\006Charge\022\022.payment.Ch" +
      "argeReq\032\023.payment.ChargeResp\"\000B\t\n\007paymen" +
      "tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_payment_CreditCardInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_payment_CreditCardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_CreditCardInfo_descriptor,
        new java.lang.String[] { "CreditCardNumber", "CreditCardCvv", "CreditCardExpirationYear", "CreditCardExpirationMonth", });
    internal_static_payment_ChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_payment_ChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_ChargeReq_descriptor,
        new java.lang.String[] { "Amount", "CreditCard", "OrderId", "UserId", });
    internal_static_payment_ChargeResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_payment_ChargeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_ChargeResp_descriptor,
        new java.lang.String[] { "TransactionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
