// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package /api;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(/api.Api.rawBody);
    registry.add(/api.Api.query);
    registry.add(/api.Api.header);
    registry.add(/api.Api.cookie);
    registry.add(/api.Api.body);
    registry.add(/api.Api.path);
    registry.add(/api.Api.vd);
    registry.add(/api.Api.form);
    registry.add(/api.Api.jsConv);
    registry.add(/api.Api.fileName);
    registry.add(/api.Api.none);
    registry.add(/api.Api.formCompatible);
    registry.add(/api.Api.jsConvCompatible);
    registry.add(/api.Api.fileNameCompatible);
    registry.add(/api.Api.noneCompatible);
    registry.add(/api.Api.goTag);
    registry.add(/api.Api.get);
    registry.add(/api.Api.post);
    registry.add(/api.Api.put);
    registry.add(/api.Api.delete);
    registry.add(/api.Api.patch);
    registry.add(/api.Api.options);
    registry.add(/api.Api.head);
    registry.add(/api.Api.any);
    registry.add(/api.Api.genPath);
    registry.add(/api.Api.apiVersion);
    registry.add(/api.Api.tag);
    registry.add(/api.Api.name);
    registry.add(/api.Api.apiLevel);
    registry.add(/api.Api.serializer);
    registry.add(/api.Api.param);
    registry.add(/api.Api.baseurl);
    registry.add(/api.Api.handlerPath);
    registry.add(/api.Api.handlerPathCompatible);
    registry.add(/api.Api.httpCode);
    registry.add(/api.Api.baseDomain);
    registry.add(/api.Api.baseDomainCompatible);
    registry.add(/api.Api.servicePath);
    registry.add(/api.Api.reserve);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int RAW_BODY_FIELD_NUMBER = 50101;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> rawBody = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int QUERY_FIELD_NUMBER = 50102;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> query = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HEADER_FIELD_NUMBER = 50103;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> header = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int COOKIE_FIELD_NUMBER = 50104;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> cookie = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int BODY_FIELD_NUMBER = 50105;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> body = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PATH_FIELD_NUMBER = 50106;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> path = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int VD_FIELD_NUMBER = 50107;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> vd = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FORM_FIELD_NUMBER = 50108;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> form = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int JS_CONV_FIELD_NUMBER = 50109;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> jsConv = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FILE_NAME_FIELD_NUMBER = 50110;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fileName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NONE_FIELD_NUMBER = 50111;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> none = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FORM_COMPATIBLE_FIELD_NUMBER = 50131;
  /**
   * <pre>
   * 50131~50160 used to extend field option by hz
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> formCompatible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int JS_CONV_COMPATIBLE_FIELD_NUMBER = 50132;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> jsConvCompatible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FILE_NAME_COMPATIBLE_FIELD_NUMBER = 50133;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fileNameCompatible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NONE_COMPATIBLE_FIELD_NUMBER = 50134;
  /**
   * <pre>
   * 50135 is reserved to vt_compatible
   * optional FieldRules vt_compatible = 50135;
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> noneCompatible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GO_TAG_FIELD_NUMBER = 51001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> goTag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GET_FIELD_NUMBER = 50201;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> get = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int POST_FIELD_NUMBER = 50202;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> post = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PUT_FIELD_NUMBER = 50203;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> put = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DELETE_FIELD_NUMBER = 50204;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> delete = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PATCH_FIELD_NUMBER = 50205;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> patch = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONS_FIELD_NUMBER = 50206;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> options = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HEAD_FIELD_NUMBER = 50207;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> head = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ANY_FIELD_NUMBER = 50208;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> any = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int GEN_PATH_FIELD_NUMBER = 50301;
  /**
   * <pre>
   * The path specified by the user when the client code is
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> genPath = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int API_VERSION_FIELD_NUMBER = 50302;
  /**
   * <pre>
   * generated, with a higher priority than api_version
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> apiVersion = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TAG_FIELD_NUMBER = 50303;
  /**
   * <pre>
   * client code is generated
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> tag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NAME_FIELD_NUMBER = 50304;
  /**
   * <pre>
   * Name of rpc
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> name = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int API_LEVEL_FIELD_NUMBER = 50305;
  /**
   * <pre>
   * Interface Level
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> apiLevel = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERIALIZER_FIELD_NUMBER = 50306;
  /**
   * <pre>
   * Serialization method
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> serializer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PARAM_FIELD_NUMBER = 50307;
  /**
   * <pre>
   * Whether client requests take public parameters
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> param = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int BASEURL_FIELD_NUMBER = 50308;
  /**
   * <pre>
   * Baseurl used in ttnet routing
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> baseurl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HANDLER_PATH_FIELD_NUMBER = 50309;
  /**
   * <pre>
   * handler_path specifies the path to generate the method
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> handlerPath = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HANDLER_PATH_COMPATIBLE_FIELD_NUMBER = 50331;
  /**
   * <pre>
   * 50331~50360 used to extend method option by hz
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.String> handlerPathCompatible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int HTTP_CODE_FIELD_NUMBER = 50401;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.Integer> httpCode = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int BASE_DOMAIN_FIELD_NUMBER = 50402;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> baseDomain = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int BASE_DOMAIN_COMPATIBLE_FIELD_NUMBER = 50731;
  /**
   * <pre>
   * 50731~50760 used to extend service option by hz
   * </pre>
   *
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> baseDomainCompatible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SERVICE_PATH_FIELD_NUMBER = 50732;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.String> servicePath = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int RESERVE_FIELD_NUMBER = 50830;
  /**
   * <pre>
   * 550831 is reserved to msg_vt_compatible
   * optional FieldRules msg_vt_compatible = 50831;
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> reserve = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\003api\032 google/protobuf/descri" +
      "ptor.proto:4\n\010raw_body\022\035.google.protobuf" +
      ".FieldOptions\030\265\207\003 \001(\t\210\001\001:1\n\005query\022\035.goog" +
      "le.protobuf.FieldOptions\030\266\207\003 \001(\t\210\001\001:2\n\006h" +
      "eader\022\035.google.protobuf.FieldOptions\030\267\207\003" +
      " \001(\t\210\001\001:2\n\006cookie\022\035.google.protobuf.Fiel" +
      "dOptions\030\270\207\003 \001(\t\210\001\001:0\n\004body\022\035.google.pro" +
      "tobuf.FieldOptions\030\271\207\003 \001(\t\210\001\001:0\n\004path\022\035." +
      "google.protobuf.FieldOptions\030\272\207\003 \001(\t\210\001\001:" +
      ".\n\002vd\022\035.google.protobuf.FieldOptions\030\273\207\003" +
      " \001(\t\210\001\001:0\n\004form\022\035.google.protobuf.FieldO" +
      "ptions\030\274\207\003 \001(\t\210\001\001:3\n\007js_conv\022\035.google.pr" +
      "otobuf.FieldOptions\030\275\207\003 \001(\t\210\001\001:5\n\tfile_n" +
      "ame\022\035.google.protobuf.FieldOptions\030\276\207\003 \001" +
      "(\t\210\001\001:0\n\004none\022\035.google.protobuf.FieldOpt" +
      "ions\030\277\207\003 \001(\t\210\001\001:;\n\017form_compatible\022\035.goo" +
      "gle.protobuf.FieldOptions\030\323\207\003 \001(\t\210\001\001:>\n\022" +
      "js_conv_compatible\022\035.google.protobuf.Fie" +
      "ldOptions\030\324\207\003 \001(\t\210\001\001:@\n\024file_name_compat" +
      "ible\022\035.google.protobuf.FieldOptions\030\325\207\003 " +
      "\001(\t\210\001\001:;\n\017none_compatible\022\035.google.proto" +
      "buf.FieldOptions\030\326\207\003 \001(\t\210\001\001:2\n\006go_tag\022\035." +
      "google.protobuf.FieldOptions\030\271\216\003 \001(\t\210\001\001:" +
      "0\n\003get\022\036.google.protobuf.MethodOptions\030\231" +
      "\210\003 \001(\t\210\001\001:1\n\004post\022\036.google.protobuf.Meth" +
      "odOptions\030\232\210\003 \001(\t\210\001\001:0\n\003put\022\036.google.pro" +
      "tobuf.MethodOptions\030\233\210\003 \001(\t\210\001\001:3\n\006delete" +
      "\022\036.google.protobuf.MethodOptions\030\234\210\003 \001(\t" +
      "\210\001\001:2\n\005patch\022\036.google.protobuf.MethodOpt" +
      "ions\030\235\210\003 \001(\t\210\001\001:4\n\007options\022\036.google.prot" +
      "obuf.MethodOptions\030\236\210\003 \001(\t\210\001\001:1\n\004head\022\036." +
      "google.protobuf.MethodOptions\030\237\210\003 \001(\t\210\001\001" +
      ":0\n\003any\022\036.google.protobuf.MethodOptions\030" +
      "\240\210\003 \001(\t\210\001\001:5\n\010gen_path\022\036.google.protobuf" +
      ".MethodOptions\030\375\210\003 \001(\t\210\001\001:8\n\013api_version" +
      "\022\036.google.protobuf.MethodOptions\030\376\210\003 \001(\t" +
      "\210\001\001:0\n\003tag\022\036.google.protobuf.MethodOptio" +
      "ns\030\377\210\003 \001(\t\210\001\001:1\n\004name\022\036.google.protobuf." +
      "MethodOptions\030\200\211\003 \001(\t\210\001\001:6\n\tapi_level\022\036." +
      "google.protobuf.MethodOptions\030\201\211\003 \001(\t\210\001\001" +
      ":7\n\nserializer\022\036.google.protobuf.MethodO" +
      "ptions\030\202\211\003 \001(\t\210\001\001:2\n\005param\022\036.google.prot" +
      "obuf.MethodOptions\030\203\211\003 \001(\t\210\001\001:4\n\007baseurl" +
      "\022\036.google.protobuf.MethodOptions\030\204\211\003 \001(\t" +
      "\210\001\001:9\n\014handler_path\022\036.google.protobuf.Me" +
      "thodOptions\030\205\211\003 \001(\t\210\001\001:D\n\027handler_path_c" +
      "ompatible\022\036.google.protobuf.MethodOption" +
      "s\030\233\211\003 \001(\t\210\001\001:9\n\thttp_code\022!.google.proto" +
      "buf.EnumValueOptions\030\341\211\003 \001(\005\210\001\001:9\n\013base_" +
      "domain\022\037.google.protobuf.ServiceOptions\030" +
      "\342\211\003 \001(\t\210\001\001:D\n\026base_domain_compatible\022\037.g" +
      "oogle.protobuf.ServiceOptions\030\253\214\003 \001(\t\210\001\001" +
      "::\n\014service_path\022\037.google.protobuf.Servi" +
      "ceOptions\030\254\214\003 \001(\t\210\001\001:5\n\007reserve\022\037.google" +
      ".protobuf.MessageOptions\030\216\215\003 \001(\t\210\001\001B\006\n\004/" +
      "apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    rawBody.internalInit(descriptor.getExtensions().get(0));
    query.internalInit(descriptor.getExtensions().get(1));
    header.internalInit(descriptor.getExtensions().get(2));
    cookie.internalInit(descriptor.getExtensions().get(3));
    body.internalInit(descriptor.getExtensions().get(4));
    path.internalInit(descriptor.getExtensions().get(5));
    vd.internalInit(descriptor.getExtensions().get(6));
    form.internalInit(descriptor.getExtensions().get(7));
    jsConv.internalInit(descriptor.getExtensions().get(8));
    fileName.internalInit(descriptor.getExtensions().get(9));
    none.internalInit(descriptor.getExtensions().get(10));
    formCompatible.internalInit(descriptor.getExtensions().get(11));
    jsConvCompatible.internalInit(descriptor.getExtensions().get(12));
    fileNameCompatible.internalInit(descriptor.getExtensions().get(13));
    noneCompatible.internalInit(descriptor.getExtensions().get(14));
    goTag.internalInit(descriptor.getExtensions().get(15));
    get.internalInit(descriptor.getExtensions().get(16));
    post.internalInit(descriptor.getExtensions().get(17));
    put.internalInit(descriptor.getExtensions().get(18));
    delete.internalInit(descriptor.getExtensions().get(19));
    patch.internalInit(descriptor.getExtensions().get(20));
    options.internalInit(descriptor.getExtensions().get(21));
    head.internalInit(descriptor.getExtensions().get(22));
    any.internalInit(descriptor.getExtensions().get(23));
    genPath.internalInit(descriptor.getExtensions().get(24));
    apiVersion.internalInit(descriptor.getExtensions().get(25));
    tag.internalInit(descriptor.getExtensions().get(26));
    name.internalInit(descriptor.getExtensions().get(27));
    apiLevel.internalInit(descriptor.getExtensions().get(28));
    serializer.internalInit(descriptor.getExtensions().get(29));
    param.internalInit(descriptor.getExtensions().get(30));
    baseurl.internalInit(descriptor.getExtensions().get(31));
    handlerPath.internalInit(descriptor.getExtensions().get(32));
    handlerPathCompatible.internalInit(descriptor.getExtensions().get(33));
    httpCode.internalInit(descriptor.getExtensions().get(34));
    baseDomain.internalInit(descriptor.getExtensions().get(35));
    baseDomainCompatible.internalInit(descriptor.getExtensions().get(36));
    servicePath.internalInit(descriptor.getExtensions().get(37));
    reserve.internalInit(descriptor.getExtensions().get(38));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
